### ISSUE TITLE
Add an option to notate in the protection log when an action originated from a request at RFPP

### ISSUE THREAD

**Issue by molly** [wikimedia-gadgets/twinkle#1247]
I often find myself manually notating logs when I protect a page from a request at RfPP. I think it would be handy to have a checkbox that does this for me, but wanted to see if there's any other interest in this before submitting a patch myself.

**Comment by Amorymeltzer** [comment]
I suppose so; you're certainly not the only one.  If you're interested in submitting it, something like the logic used for the see_alsos in the block module could do it.

TBH I've always wondered what the advantage of noting just that it was a request at RfPP, without a direct link or anything.  A revid (with or without a section title) could be more useful, since we could create a permalink, but I think it might be too clunky and underused.
