### ISSUE TITLE
Abstract out mediawiki mocking code to a separate repository

### ISSUE THREAD

**Issue by siddharthvp** [wikimedia-gadgets/twinkle#1260]
The repo could be called `mock-mediawiki`. This would enable everyone to use it – different twinkle installations, the twinkle core itself, and even other gadgets and user scripts. 

It would be worth enhancing the setup to allow for multiple sets of mw.configs. Things like that would be overkill to do for this one project, but would make sense when it's a reusable package.

I think @evad37 also has some mediawiki mocking code in xfd-closer which could be merged in.

**Comment by evad37** [comment]
Yeah, I use mocks for running unit tests in a node environment. My build/test steps switch between https://github.com/wikimedia-gadgets/xfdcloser/blob/master/globals-src/window.js (window versions of jQuery, mw object, and OOjs) and https://github.com/wikimedia-gadgets/xfdcloser/blob/master/globals-src/node.js (which uses imported non packages and it's own minimal functions/objects, including https://github.com/wikimedia-gadgets/xfdcloser/blob/master/mocks/mockMwTitle.js )

**Comment by siddharthvp** [comment]
@evad37 I see you're using https://github.com/wikimedia/mediawiki-title and using it to shim `mw.Title`. Is there a reason to not simply copy from the MW source code? I would think that would be more robust as well as easier.

**Comment by evad37** [comment]
@siddharthvp There were two reasons I didn't:

1. Licensing: MW core is GPL, so a simple copy would also have to be GPL licenced
2. It's not just [Title.js](https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/core/+/refs/heads/master/resources/src/mediawiki.Title/Title.js) since that file also makes use of mediawiki.String.js, phpCharToUpper.json, mw.config, and mw.util (and whatever those depend on)

These shouldn't be problems for a new repo that wants to mock a whole lot of mediawiki code, but at the time it seemed simpler to do the shim.

**Comment by siddharthvp** [comment]
Ah yeah, fair points. The mocking currently on this repo is indeed licensing-invalid. My idea to deal with it is to make `mock-mediawiki` LGPL-licensed. LGPL is GPL-compatible (and so can contain copy of GPL-licensed code), but unlike GPL, LGPL projects can be used as a library even by non-(L)GPL projects.

**Comment by siddharthvp** [comment]
@evad37 @Amorymeltzer https://github.com/wikimedia-gadgets/mock-mediawiki is created.
