### ISSUE TITLE
Bad edit request for RfD nominations

### ISSUE THREAD

**Issue by pppery** [wikimedia-gadgets/twinkle#1303]
See https://en.wikipedia.org/wiki/Wikipedia_talk:RFP#Edit_request_to_complete_RfD_nomination. The request says to add unclosed template syntax.

**Comment by Amorymeltzer** [comment]
Yeah... this is because we use [{{Xfd edit protected}}](https://en.wikipedia.org/wiki/Template:Xfd_edit_protected), and RfD is the only one to need something else, so it was left off.  I suppose the thing to do would be to add a `rfd=yes` parameter or something to the template which rewords it to something to the effect of

>[top of the page] and `}}` to the bottom to [complete the nomination].

We can then use that parameter here.  It's a bit ugly IMO, but I'm not sure there's another way without making the template itself less useful on-wiki for non-Twinkle.  I tossed it together at [Template:Xfd_edit_protected/sandbox](https://en.wikipedia.org/wiki/Template:Xfd_edit_protected/sandbox), thoughts?  cc @siddharthvp

**Comment by siddharthvp** [comment]
@Amorymeltzer Sounds right to me.

**Comment by Amorymeltzer** [comment]
Template now updated (thanks @siddharthvp) so gonna go do #1305
