### ISSUE TITLE
Article tagging - when tags already present and ungrouped, not able to group them

### ISSUE THREAD

**Issue by RedDragonWebDesign** [wikimedia-gadgets/twinkle#1334]
When tagging articles with maintenance tags, if tags already exist and they are not grouped, and the user has the "group inside" checkbox checked, consider not throwing an error message. This would allow the user to quickly group them.

To reproduce:

- Go to https://en.wikipedia.org/w/index.php?title=Dennis_Inyang&oldid=1008637658
- TW -> Tag
- (there's already 3 tags, but they are not grouped)
- make sure "Group inside" is checked
- hit "Submit Query"
- You get a JS browser alert saying "You must select at least one tag!"

**Comment by Amorymeltzer** [comment]
I've thought about this a few times in the past, but I really don't think it's worth it.  It's a perfect task for a bot and, lo, https://en.wikipedia.org/wiki/Wikipedia:Bots/Requests_for_approval/Cewbot_5

**Comment by NovemLinguae** [comment]
This code path is complicated. Would require a lot of testing to ensure it's bug free. Article with multiple issues ticked, article without multiple issues ticked, redirect. Add tag, no change, remove tag. etc.

I think I'd rather make a ticket to remove the "Group inside {{multiple issues}} if possible" check box, and just do that always by default. That would simplify the code instead of making it more complex.
