### ISSUE TITLE
Support for Timeless skin

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/twinkle#1521]
Requested by Vitaium at https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#New_features_request

**Comment by MusikAnimal** [comment]
Twinkle is available in Timeless. Look for the "Twinkle" heading on the right-side. Are you instead requesting dropdown menu support? That's what #716 is about. Twinkle is also available in Monobook and Modern, they are just a list of bare links instead of menu as seen in Vector.

I don't know how we'd do menus in Timeless, since there isn't really anywhere to put to a dropdown menu across the top.

**Comment by NovemLinguae** [comment]
Yeap looks like we already have support for it. Thanks for pointing out, and for an excuse to look at these skins I've never visited. Closing.

![image](https://user-images.githubusercontent.com/79697282/155636365-be23b111-c036-4538-8909-74df2f47e8de.png)
