### ISSUE TITLE
warn: Uncaught TypeError: $(...).select2 is not a function

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/twinkle#1628]
Steps to reproduce
- Possibly optional: make sure testwiki User_talk:NovemBot is deleted / doesn't exist
- Visit https://test.wikipedia.org/w/index.php?title=User_talk:NovemBot&action=edit&redlink=1&vanarticle=Test

Unable to consistently reproduce

What happens?
<img width="525" alt="2022-08-01_140828" src="https://user-images.githubusercontent.com/79697282/182247389-d93e75f3-ea0a-4c09-af2d-edc9cd089e4d.png">
<img width="537" alt="2022-08-01_140952" src="https://user-images.githubusercontent.com/79697282/182247400-a3afb038-946e-4518-9e07-fa8e6d4e9411.png">

**Comment by siddharthvp** [comment]
It's because the `ext.gadget.select2` RL module somehow hasn't loaded. 

Is this while using the `npm start` script? The script only does lazy load via mw.loader.load: https://github.com/wikimedia-gadgets/twinkle/blob/f05d99c689d8d0e8e96dfcfbe83c2bd64257645b/scripts/dev-server.js#L20

Wrapping `jsCode` with mw.loader.using statement should fix the issue, I think.

**Comment by NovemLinguae** [comment]
Yes it was while using `npm start`

So the fix is to just change "load" to "using"?

**Comment by siddharthvp** [comment]
Not quite. mw.loader.using returns a promise; we have to put all remaining code in a `.then()` callback, which ensures select2 will be available when the remaining code runs.
