### ISSUE TITLE
tag: detection of existing redirects should be case insensitive

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/twinkle#1673]
Mentioned in https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Add_rcat_shell_more_easily

> For example, if the redirect has a tag "r from misspelling" and you select the same tag in Twinkle hoping to add the rcat shell, Twinkle adds the shell and "R from misspelling" - you get two tags due to the different capitalization. -MB

**Comment by Trialpearswiki** [comment]
The description of this issue seems to be incorrect. The testing if the template already exists (line 1741) is insensitive which also was the result of my tests. It does not check for redirects however which is probably what was actually happening here. That is a significantly more difficult problem to solve.

**Comment by NovemLinguae** [comment]
Confirmed. This ticket as originally described is invalid. Thanks @Trialpearswiki. Will close.

<img width="734" alt="image" src="https://user-images.githubusercontent.com/79697282/221033102-3e90e903-efe5-478b-bf5c-7f2baf3e6ac8.png">
