### ISSUE TITLE
arv: aiv screen grays out some check boxes when reporting an IP

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/twinkle#1962]
Requested by RichSmith on IRC

I suspect the grayed out ones are offers to report to WP:UAA (which you can't do for an IP), and the non grayed out ones are offers to report to WP:AIV (which you can do for an IP). However I should look at the code and double check that these are all correct.

* [ ] make sure the 2 grayed out ones report to WP:UAA, and therefore should be grayed out
* [ ] make sure that "Account is evidently a spambot or a compromised account" (not grayed out) does not report to UAA (seems like it might, maybe it needs to be grayed out)

<img width="695" alt="image" src="https://github.com/wikimedia-gadgets/twinkle/assets/79697282/0f0e37b6-93bb-436e-b204-26e1f02b6ce1">

**Comment by TollensWP** [comment]
All of these checkboxes report to AIV; UAA reporting is under a different category in the dropdown at the top of that dialog box. However, it is correct that they are grayed out: it does not make sense to report an IP editor as a "vandalism/promotion-only account" because they do not have an account and other people may be using the IP (see [Wikipedia:Vandalism-only account](https://en.wikipedia.org/wiki/Wikipedia:Vandalism-only_account)).

**Comment by NovemLinguae** [comment]
Ah, makes sense. Thanks!
