### ISSUE TITLE
Add new C4 criterion

### ISSUE THREAD

**Issue by pppery** [wikimedia-gadgets/twinkle#1994]
Per https://en.wikipedia.org/wiki/Wikipedia_talk:Criteria_for_speedy_deletion/Archive_89#C4_%E2%80%93_unused_maintenance_categories

This replaces {{db-templatecat}}

**Comment by NovemLinguae** [comment]
I see some code in modules/twinklespeedy.js related to "templatecat".

<img width="595" alt="image" src="https://github.com/user-attachments/assets/e4d1cbad-192e-49ed-8ea1-31326cbd51ce">

But when I go try to tag https://en.wikipedia.org/wiki/Category:Sandbox with TW -> CSD, I do not see anything like "G8: Categories populated by a deleted or retargeted template" in the list of CSD tags. Any idea why?

**Comment by NovemLinguae** [comment]
Also requested by Liz and @primefac

**Comment by TollensWP** [comment]
In the case of https://en.wikipedia.org/wiki/Category:Sandbox, the category CSD tag list doesn't come up because the category is a soft redirect – that's also why the redirects tag list comes up. If you try the same at https://en.wikipedia.org/wiki/Category:Xn that tag does appear.
It would seem to me that the second G8 tag option in your screenshot above shouldn't be there also, since that will never show up on any page it's applicable to. I'll pull both out and replace with C4.
