### ISSUE TITLE
Stick a license in the GitHub repo

### ISSUE THREAD

**Issue by Ironholds** [wikimedia-gadgets/twinkle#252]
The repo doesn't have a license. Suggest putting one in? CC-0 or CC-BY-SA 3.0 or MIT or...whatever.

**Comment by marioxcc** [comment]
I suggest the GNU General Public License 3 or any later version because it is a Copyleft license (See https://www.gnu.org/philosophy/pragmatic.html). Currently, as it stands, we can't tell from this repository that Twinkle is free software. All on the contrary, due to the lack of license and the Berne Convention, we could deduce that it's proprietary software (See https://www.gnu.org/licenses/license-list.html#NoLicense). However, since some versions has been published in Wikipedia, those versions are under the Creative Commons BY-SA 3.0 and so are free software. But the CC BY-SA 3.0 is not designed for software (Creative Commons [recommends against](https://wiki.creativecommons.org/Faq#Can_I_apply_a_Creative_Commons_license_to_software.3F) using it for software). The GNU GPL 3 (and other versions) is designed for software, and it's analogous to the CC BY-SA.

I suggest to dual-license Twinkle adding the GNU GPL 3. The CC BY-SA 3.0 is alredy given because Twinkle has been publised in Wikipedia, but currently as this repository stands, it fails to comply with that license (See section 4c for an *example* of requirements not complied with). The Copyright holder need not to comply with his own license, but since Twinkle is a collabovrative work, all of the non-trivial contributors hold a Copyright on it (which they must license under the CC BY-SA 3.0 because of the Copyleft, but they can also license their own contributions under another additional license, see the Wikipedia and GNU pages on licenses for more information).

**Comment by Technical-13** [comment]
Per http://en.wikipedia.org/wiki/MediaWiki:Wikimedia-copyrightwarning `By clicking the "Save page" button, you agree to the Terms of Use and you irrevocably agree to release your contribution under the CC BY-SA 3.0 License and the GFDL with the understanding that a hyperlink or URL is sufficient for CC BY-SA 3.0 attribution.` it's released under both CC BY-SA 3.0 and GFDL and the links from here back to Wikipedia are sufficient for attribution.  This means that there is no violation here. Also, since V2.0 has been on GitHub since May 29, 2011 and was copied to Wikipedia from here ( http://en.wikipedia.org/w/index.php?title=MediaWiki:Gadget-Twinkle.js&oldid=431552495 ), this can not bed a copyright violation of that.

**Comment by atlight** [comment]
The repo is implicitly licensed under the CC-BY-SA 3.0/GFDL pair. We did for a time have a copy of `moment.js` in here, which was licensed under MIT or something, but as MIT is a permissive license I assume it is compatible with CC-BY-SA.

**Comment by marioxcc** [comment]
The preferred way is to include the license header in **all** files (Including, of course Makefiles and documentation). This license header may be found in the section entitled *How to Apply These Terms to Your New Programs* of the GNU General Public License version 3. Don't just include a copy of the aforesaid license, it's unclear whether that has legal validity (See https://www.gnu.org/licenses/gpl-faq.en.html#NoticeInSourceFile and https://www.gnu.org/licenses/gpl-faq.en.html#LicenseCopyOnly). Another option is including in the documentation (For example, the README file) the GNU GPL license notice, and making it clear that it applies to the whole project (including all files and commit information); this option isn't the preferred one, however. See the GNU GPL FAQ for more information.

**Comment by legoktm** [comment]
I release all my contributions to Twinkle into the public domain/CC-0 and don't care what license is eventually picked.

**Comment by theopolisme** [comment]
Easy enough (thanks Kunal for making this especially easy :smiley:)...

I release all my contributions to Twinkle into the public domain/CC-0 and don't care what license is eventually picked.

**Comment by atlight** [comment]
Let me be clear, I really don't like GPL; I find it too restrictive for a project such as Twinkle. I would be happy to release code under MIT as well as the implicit CC-BY-SA/GFDL that we have always been working under.

However, if others are fine with also licensing under GPL then I suppose I would have little choice but to agree, in the end.

Really though I would ask, what is the point of licensing under GPL if we also license under MIT? Seems completely pointless to me...

**Comment by mc10** [comment]
I'm okay with any appropriate license as long as everyone agrees. @atlight Correct me if I'm wrong, but I don't believe that we're using an MIT license at the moment.

**Comment by atlight** [comment]
No we're not at the moment, but I was to some extent replying to @azatoth's email with that comment, which proposed "releasing the code under MIT or GPL as well".

**Comment by Ankit-Maity** [comment]
I am fine with whatever the collaborators decide.

**Comment by Ironholds** [comment]
Personally, the GPL grinds my gears, but I'm not a committer and so don't directly have a dog in this race.

**Comment by Ankit-Maity** [comment]
If this site is accurate, http://choosealicense.com/licenses/
I guess, makes it easier to understand. 
If we use MIT, I would rather choose EPL 1.0, since it also involves disclosing the source of the source code and grants "Patent Grants".

**Comment by throwaway1037** [comment]
Please may I ask about the status of this issue? An explicit license is extremely important because it is what makes a program free.

I understand code imprted from Wikipedia is licensed under the terms of either CC-BY-SA-3.0 (-only or -or-later?) or GFDL (which version? -only or -or-later?) but that doesn't automatically apply to git commits by people who did not agree to releasing code they authored under such terms and conditions.

**Comment by atlight** [comment]
I think this is still true:

> The repo is implicitly licensed under the CC-BY-SA 3.0/GFDL pair.

I would tend to ignore GFDL here - it's an inappropriate license for code. So in effect, Twinkle's license is CC-BY-SA-3.0-only (Wikipedia doesn't automatically adopt later versions), except for the parts mentioned in the README which are available under different licenses.

**Comment by throwaway1037** [comment]
Please may this be double-checked and stated explicitly? Are you sure all contributors agreed to this arrangement?
